version: '3'
services:
  jenkins:
    image: opsify/jenkins
    container_name: jenkins_server
    restart: unless-stopped
    environment:
      - JENKINS_ADMIN_ID=admin
      - JENKINS_ADMIN_PASSWORD=password
    ports:
      - 8080:8080
    networks:
      - jenkins

  setup_jenkins:
    image: opsify/jenkins_cli
    environment:
      - JENKINS_ADMIN_ID=admin
      - JENKINS_ADMIN_PASSWORD=password
    container_name: setup_jenkins
    command: bash /opt/createjobs.sh
    networks:
      - jenkins

networks:
  jenkins:
    driver: bridge
